### ISSUE TITLE
L'app è morta

### ISSUE THREAD

**Issue by aleeeee1** [Gabboxl/PininOrario#306]
non c'è un singolo link funzionante nell'app apparte quelli di github
;-;

**Comment by Gabboxl** [comment]
Ciao, durante questa estate purtroppo non ho avuto molto tempo da dedicare all'app, a breve riprenderò lo sviluppo.
Riguardo ai link che non funzionano, a quali ti riferisci? Se parli dei siti da dove vengono scaricati gli orari, essi sono stati sostituiti da una libreria apposita nel branch di sviluppo https://github.com/Gabboxl/PininOrario/tree/pininorarioV2, e attualmente sembra funzionare molto bene.

**Comment by aleeeee1** [comment]
Ho scaricato la repo di pininorariov2 e ho anche compilato ma non funziona nulla. mi dice che i siti sono down e se provo ad accedervi (ad esempio https://gabboxlbot.altervista.org/pininorario/periodi.php oppure https://pinin.gabboxl.ga/versions/update.json) risultano effettivamente offline

**Comment by aleeeee1** [comment]
Sono un coglione

**Comment by Gabboxl** [comment]
Hahaha, comunque se dovesse servire aiuto per qualunque cosa chiedi pure : ))
